apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "nginx-sample.fullname" . }}-vs
spec:
  gateways:
  - {{ include "nginx-sample.fullname" . }}-gw
  hosts:
  - '*'
  http:
  - name: primary
    match:
    - uri:
        prefix: /active/
    - uri:
        exact: /active  
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "nginx-sample.fullname" . }}-active
        subset: active
        port:
          number: 80
      weight: 100
  - name: secondary
    match:
    - uri:
        prefix: /preview/
    - uri:
        exact: /preview
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "nginx-sample.fullname" . }}-preview
        subset: preview
        port:
          number: 80
      weight: 100      
    #- destination:
     #   host: {{ include "nginx-sample.fullname" . }}-preview
      #  subset: preview
       # port:
        #  number: 80
      #weight: 0
